// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_withdraw_callback_url`, `fetch_invoice`, `fetch_json`, `fetch_pay_params`, `fetch_withdraw_params`, `is_lnurl_or_address`, `parse_withdraw_response`, `service_reason`, `submit_withdraw_invoice`, `verify_invoice`, `withdraw_uri_to_http`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

/// Parameters returned by a LNURLw (LNURL Withdraw) endpoint.
/// Shown to the user before they confirm a Boltcard withdraw.
class LnurlWithdrawParams {
  final String callback;
  final String k1;
  final BigInt minWithdrawableMsats;
  final BigInt maxWithdrawableMsats;
  final String defaultDescription;

  const LnurlWithdrawParams({
    required this.callback,
    required this.k1,
    required this.minWithdrawableMsats,
    required this.maxWithdrawableMsats,
    required this.defaultDescription,
  });

  @override
  int get hashCode =>
      callback.hashCode ^
      k1.hashCode ^
      minWithdrawableMsats.hashCode ^
      maxWithdrawableMsats.hashCode ^
      defaultDescription.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LnurlWithdrawParams &&
          runtimeType == other.runtimeType &&
          callback == other.callback &&
          k1 == other.k1 &&
          minWithdrawableMsats == other.minWithdrawableMsats &&
          maxWithdrawableMsats == other.maxWithdrawableMsats &&
          defaultDescription == other.defaultDescription;
}
